#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: filebrowser-root-pvc
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 10Gi  # Adjust size as needed
#---



apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: filebrowser-db-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: filebrowser-config-pv














