apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/sftp-data/filebrowser-db/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/sftp-data/filebrowser-config/
