apiVersion: v1
kind: PersistentVolume
metadata:
  name: sftp-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/sftp-data  # Change this path for your environment
