apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: sftp-data
          persistentVolumeClaim:
            claimName: sftp-pvc
        - name: config-volume
          configMap:
            name: nginx-config
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: sftp-data
              mountPath: /var/www/html  # Nginx default web root
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: php-fpm
          image: php:8.1-fpm
          volumeMounts:
            - name: sftp-data
              mountPath: /var/www/html/

