apiVersion: v1
kind: Service
metadata:
  name: php-fpm  # This must match what is in "fastcgi_pass php-fpm:9000"
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
