apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sftpReplicaOne
  labels:
    app: sftp
    system: sftpReplicaOne
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      system: sftpReplicaOne
  template:
    metadata:
      labels:
        system: sftpReplicaOne
    spec:
      containers:
      - name: sftp
        image: atmoz/sftp:latest
